---
- name: create /www/ directory
  file: dest={{project_root}} state=directory owner=www-data group=www-data mode=0700

- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Change default nginx site
  sudo: yes
  template: src={{ ws_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_file }}
  notify: restart nginx