---
- hosts: devserver
  sudo: true
  vars:
    web_server: nginxphp
    vagrant_user: true
    web_applications_user: vagrant_user
    webserver_user: vagrant
    timezone: Europe/London
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - vars/nginxphp.yml
    - vars/hosts_dev.yml
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - mysql
    - phpcommon
    - app
    - composer
    - gulp
    - laravel-env
